DROP TABLE Zaposleni cascade constraints;
DROP TABLE Taxi_Vozilo cascade constraints;
DROP TABLE Redovna_Musterija cascade constraints;
DROP TABLE Sopstveno_Vozilo cascade constraints;
DROP TABLE Voznja cascade constraints;
DROP TABLE Dodeljeno cascade constraints;
DROP TABLE Broj_Telefona cascade constraints;
DROP SEQUENCE SOPVOZILO_ID_SEQ;
DROP SEQUENCE VOZNJA_ID_SEQ;
DROP SEQUENCE DODELJENO_ID_SEQ;
DROP SEQUENCE BRTEL_ID_SEQ;

------ID_SOPVOZILO SEQUENCE--------
CREATE SEQUENCE SOPVOZILO_ID_SEQ
MINVALUE 1 MAXVALUE 99999
START WITH 1 INCREMENT BY 1 CACHE 20
NOORDER NOCYCLE;
-----------------------------------
------ID_VOZNJE SEQUENCE-----------
CREATE SEQUENCE VOZNJA_ID_SEQ
MINVALUE 1 MAXVALUE 99999
START WITH 1 INCREMENT BY 1 CACHE 20 
NOORDER NOCYCLE;
-----------------------------------
------ID_DODELJENO SEQ------
CREATE SEQUENCE DODELJENO_ID_SEQ
MINVALUE 1 MAXVALUE 9999999
START WITH 1 INCREMENT BY 1 CACHE 20 
ORDER NOCYCLE;
-----------------------------------
------ID_BRTEL SEQUENCE------------
CREATE SEQUENCE BRTEL_ID_SEQ
MINVALUE 1 MAXVALUE 9999999
START WITH 1 INCREMENT BY 1 CACHE 20 
NOORDER NOCYCLE;
-----------------------------------

CREATE TABLE Zaposleni(
    JMBG VARCHAR2(13) NOT NULL,
    LIme VARCHAR(20),
    SSlovo CHAR(1),
    Prezime VARCHAR(20),
    Adresa VARCHAR(50),
    BrojTelefona VARCHAR(10),
    TipZaposleni VARCHAR(5) NOT NULL, 
    Kategorija CHAR(1),
    BrVDozvole VARCHAR2(9),
    StrucnaSprema VARCHAR2(60)
);
CREATE TABLE Redovna_Musterija(
    ID_Musterija NUMBER(5,0),
    Adresa VARCHAR(50),
    BrojKoriscenihVoznji SMALLINT DEFAULT 0,
    Popust DECIMAL(3,2) 
);
CREATE TABLE Taxi_Vozilo(
    RegOznaka VARCHAR(8) NOT NULL,
    Marka VARCHAR(20),
    Tip VARCHAR(15),
    DatumIstekaReg DATE NOT NULL,
    GodinaProizvodnje NUMBER(4)
);
CREATE TABLE Sopstveno_Vozilo(
    ID_Vozilo NUMBER(5,0), 
    JMBG_Vozaca VARCHAR(13),
    TipVozila VARCHAR(15),
    Boja VARCHAR(20),
    Marka VARCHAR(20),
    DatumOd DATE NOT NULL,
    DatumDo DATE
);
CREATE TABLE Voznja(
    ID_Voznja NUMBER(7,0), 
    PStanica VARCHAR(50) NOT NULL,
    KStanica VARCHAR(50),
    PVreme TIMESTAMP NOT NULL,
    KVreme TIMESTAMP,
    BrojPoziva VARCHAR(10) NOT NULL,
    VremePrimPoziva TIMESTAMP,
    JMBG_V VARCHAR2(13) NOT NULL, 
    JMBG_A VARCHAR2(13) NOT NULL,
    ID_Musterija NUMBER(5,0)
);
CREATE TABLE Dodeljeno(
    ID NUMBER(7,0) GENERATED BY DEFAULT AS IDENTITY, --ovde treba trigger
    RegOznaka VARCHAR(8) NOT NULL,
    JMBG_Vozaca VARCHAR2(13) NOT NULL,
    DatumOd DATE NOT NULL,
    DatumDo DATE
);
CREATE TABLE Broj_Telefona(
    ID NUMBER(7,0) NOT NULL, --trigger auto_inc
    ID_Musterija NUMBER(5,0) NOT NULL,
    BrojTelefona VARCHAR(10) NOT NULL
);


------Constraints for Table ZAPOSLENI--------------
ALTER TABLE Zaposleni ADD CONSTRAINT JMBG_PK Primary Key(JMBG) ENABLE;
ALTER TABLE Zaposleni ADD CONSTRAINT TipZaposleni_CHK CHECK (TipZaposleni in ('Vozac','Admin')) ENABLE;
---------------------------------------------------
------Constraints for Table REDOVNA_MUSTERIJA------
ALTER TABLE Redovna_Musterija ADD CONSTRAINT ID_Musterija_PK Primary Key(ID_Musterija) ENABLE;
ALTER TABLE Redovna_Musterija ADD CONSTRAINT Popust_CHK CHECK(Popust between 0 and 1) ENABLE;
---------------------------------------------------
------Constraints for Table TAXI_VOZILO-----------
ALTER TABLE Taxi_Vozilo ADD CONSTRAINT RegOznaka_PK Primary Key(RegOznaka) ENABLE;
ALTER TABLE Taxi_Vozilo ADD CONSTRAINT DatumIstekaReg_CHK CHECK(DatumIstekaReg >= DATE'1970-01-01') ENABLE;
ALTER TABLE Taxi_Vozilo ADD CONSTRAINT GodinaProizvodnje_CHK CHECK(GodinaProizvodnje >= 1970) ENABLE;
--------------------------------------------------
------Constraints for Table SOPSTVENO_VOZILO------
ALTER TABLE Sopstveno_Vozilo ADD CONSTRAINT ID_Vozilo_PK Primary Key(ID_Vozilo) ENABLE;
ALTER TABLE Sopstveno_Vozilo ADD CONSTRAINT JMBG_Vozaca_FK Foreign Key(JMBG_Vozaca) REFERENCES Zaposleni(JMBG) ENABLE;
ALTER TABLE Sopstveno_Vozilo ADD CONSTRAINT DatumSopVozilo_CHK CHECK(DatumDo >= DatumOd AND DatumOd >= DATE'1970-01-01') ENABLE;
--------------------------------------------------
------Constraints for Table VOZNJA----------------
ALTER TABLE Voznja ADD CONSTRAINT ID_Voznja_PK PRIMARY KEY(ID_Voznja) ENABLE;
ALTER TABLE Voznja ADD CONSTRAINT JMBG_V_FK Foreign Key(JMBG_V) REFERENCES Zaposleni(JMBG) ENABLE;
ALTER TABLE Voznja ADD CONSTRAINT JMBG_A_FK Foreign Key(JMBG_A) REFERENCES Zaposleni(JMBG) ENABLE;
ALTER TABLE Voznja ADD CONSTRAINT FK_CHK CHECK(JMBG_A != JMBG_V) ENABLE;
ALTER TABLE Voznja ADD CONSTRAINT ID_Musterija_FK Foreign Key(ID_Musterija) REFERENCES Redovna_Musterija(ID_Musterija) ENABLE;
ALTER TABLE Voznja ADD CONSTRAINT Vreme_CHK CHECK(KVreme >= PVreme) ENABLE;
--------------------------------------------------
-------Constraints for Table DODELJENO------------
ALTER TABLE Dodeljeno ADD CONSTRAINT Dodeljeno_PK PRIMARY KEY (RegOznaka, JMBG_Vozaca) ENABLE;
ALTER TABLE Dodeljeno ADD CONSTRAINT RegOznaka_FK FOREIGN KEY(RegOznaka) REFERENCES Taxi_Vozilo(RegOznaka) ENABLE;
ALTER TABLE Dodeljeno ADD CONSTRAINT Vozac_JMBG_FK FOREIGN KEY(JMBG_Vozaca) REFERENCES Zaposleni(JMBG) ENABLE;
ALTER TABLE Dodeljeno ADD CONSTRAINT DatumDodeljeno_CHK CHECK(DatumDo >= DatumOd AND DatumOd >= DATE'1970-01-01') ENABLE;
--------------------------------------------------
-------Constraints for Table BROJ_TELEFONA--------
ALTER TABLE Broj_Telefona ADD CONSTRAINT ID_BrTel_PK PRIMARY KEY(ID) ENABLE;
ALTER TABLE Broj_Telefona ADD CONSTRAINT Musterija_ID_FK Foreign Key(ID_Musterija) REFERENCES Redovna_Musterija(ID_Musterija) ENABLE;
--------------------------------------------------

------Trigger for ID_Vozilo_PK---------
CREATE OR REPLACE TRIGGER ID_VOZILO_PK
    BEFORE INSERT
    ON Sopstveno_Vozilo
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT SOPVOZILO_ID_SEQ.NEXTVAL into :new.ID_Vozilo FROM DUAL;
END;
/
ALTER TRIGGER ID_VOZILO_PK ENABLE;
----------------------------------------
------Trigger for ID_Voznja_PK----------
CREATE OR REPLACE TRIGGER VOZNJA_ID_PK
    BEFORE INSERT
    ON Voznja
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT VOZNJA_ID_SEQ.NEXTVAL into :new.ID_Voznja FROM DUAL;
END;
/
ALTER TRIGGER VOZNJA_ID_PK ENABLE;
-------------------------------------------
------Trigger for ID_Dodeljeno_SK----------
CREATE OR REPLACE TRIGGER ID_DODELJENO_SK
    BEFORE INSERT
    ON Dodeljeno
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT DODELJENO_ID_SEQ.NEXTVAL into :new.ID FROM DUAL;
END;
/
ALTER TRIGGER ID_DODELJENO_SK ENABLE;
----------------------------------------
------Trigger for ID_BrTel_PK-----------
CREATE OR REPLACE TRIGGER ID_BRTEL_PK
    BEFORE INSERT
    ON Broj_Telefona
    REFERENCING NEW AS NEW
    FOR EACH ROW
BEGIN
    SELECT BRTEL_ID_SEQ.NEXTVAL into :new.ID FROM DUAL;
END;
/
ALTER TRIGGER ID_BRTEL_PK ENABLE;
----------------------------------------